// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use crate::domain::todo::todo_repository::TodoRepository;
use crate::infrastructure::repositories::todo::inmemory_todo_repository::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = DcoCodec,
    default_rust_opaque = RustOpaqueNom,
    default_rust_auto_opaque = RustAutoOpaqueNom,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 863587333;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_delete_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<
        RustOpaqueNom<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>,
        >,
    >,
    id: impl CstDecode<String>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "InMemoryTodoRepository_delete", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_that = that.cst_decode();let api_id = id.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, crate::domain::todo::todo_error::TodoError>((move ||  {
                        let mut api_that_guard = None;
let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false)]);
        for i in decode_indices_ {
            match i {
                0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                _ => unreachable!(),
            }
        }
        let api_that_guard = api_that_guard.unwrap();
 let output_ok = crate::infrastructure::repositories::todo::inmemory_todo_repository::InMemoryTodoRepository::delete(&*api_that_guard, &api_id)?;   Ok(output_ok)
                    })())
                } })
}
fn wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_find_all_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<
        RustOpaqueNom<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>,
        >,
    >,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "InMemoryTodoRepository_find_all", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_that = that.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, crate::domain::todo::todo_error::TodoError>((move ||  {
                        let mut api_that_guard = None;
let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false)]);
        for i in decode_indices_ {
            match i {
                0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                _ => unreachable!(),
            }
        }
        let api_that_guard = api_that_guard.unwrap();
 let output_ok = crate::infrastructure::repositories::todo::inmemory_todo_repository::InMemoryTodoRepository::find_all(&*api_that_guard)?;   Ok(output_ok)
                    })())
                } })
}
fn wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_find_by_id_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<
        RustOpaqueNom<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>,
        >,
    >,
    id: impl CstDecode<String>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "InMemoryTodoRepository_find_by_id", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_that = that.cst_decode();let api_id = id.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, crate::domain::todo::todo_error::TodoError>((move ||  {
                        let mut api_that_guard = None;
let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false)]);
        for i in decode_indices_ {
            match i {
                0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                _ => unreachable!(),
            }
        }
        let api_that_guard = api_that_guard.unwrap();
 let output_ok = crate::infrastructure::repositories::todo::inmemory_todo_repository::InMemoryTodoRepository::find_by_id(&*api_that_guard, &api_id)?;   Ok(output_ok)
                    })())
                } })
}
fn wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_save_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<
        RustOpaqueNom<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>,
        >,
    >,
    todo: impl CstDecode<crate::domain::todo::todo_entity::Todo>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "InMemoryTodoRepository_save", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_that = that.cst_decode();let api_todo = todo.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, crate::domain::todo::todo_error::TodoError>((move ||  {
                        let mut api_that_guard = None;
let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false)]);
        for i in decode_indices_ {
            match i {
                0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                _ => unreachable!(),
            }
        }
        let api_that_guard = api_that_guard.unwrap();
 let output_ok = crate::infrastructure::repositories::todo::inmemory_todo_repository::InMemoryTodoRepository::save(&*api_that_guard, &api_todo)?;   Ok(output_ok)
                    })())
                } })
}
fn wire__crate__domain__todo__todo_state__todo_state_can_advance_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<crate::domain::todo::todo_state::TodoState>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "todo_state_can_advance",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_that = that.cst_decode();
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::domain::todo::todo_state::TodoState::can_advance(&api_that),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__domain__todo__todo_state__todo_state_can_retreat_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<crate::domain::todo::todo_state::TodoState>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "todo_state_can_retreat",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_that = that.cst_decode();
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::domain::todo::todo_state::TodoState::can_retreat(&api_that),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__domain__todo__todo_state__todo_state_can_transition_to_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<crate::domain::todo::todo_state::TodoState>,
    new_state: impl CstDecode<crate::domain::todo::todo_state::TodoState>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "todo_state_can_transition_to",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_that = that.cst_decode();
            let api_new_state = new_state.cst_decode();
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::domain::todo::todo_state::TodoState::can_transition_to(
                            &api_that,
                            api_new_state,
                        ),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl CstDecode<chrono::DateTime<chrono::Utc>> for i64 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> chrono::DateTime<chrono::Utc> {
        let flutter_rust_bridge::for_generated::Timestamp { s, ns } =
            flutter_rust_bridge::for_generated::decode_timestamp(self);
        chrono::DateTime::<chrono::Utc>::from_naive_utc_and_offset(
            chrono::DateTime::from_timestamp(s, ns)
                .expect("invalid or out-of-range datetime")
                .naive_utc(),
            chrono::Utc,
        )
    }
}
impl CstDecode<bool> for bool {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> bool {
        self
    }
}
impl CstDecode<i32> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> i32 {
        self
    }
}
impl CstDecode<i64> for i64 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> i64 {
        self
    }
}
impl CstDecode<crate::domain::todo::todo_error::TodoError> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::domain::todo::todo_error::TodoError {
        match self {
            0 => crate::domain::todo::todo_error::TodoError::EmptyDescription,
            1 => crate::domain::todo::todo_error::TodoError::InvalidStateTransition,
            2 => crate::domain::todo::todo_error::TodoError::TodoNotFound,
            _ => unreachable!("Invalid variant for TodoError: {}", self),
        }
    }
}
impl CstDecode<crate::domain::todo::todo_state::TodoState> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::domain::todo::todo_state::TodoState {
        match self {
            0 => crate::domain::todo::todo_state::TodoState::Todo,
            1 => crate::domain::todo::todo_state::TodoState::InProgress,
            2 => crate::domain::todo::todo_state::TodoState::Done,
            _ => unreachable!("Invalid variant for TodoState: {}", self),
        }
    }
}
impl CstDecode<u8> for u8 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u8 {
        self
    }
}
impl CstDecode<usize> for usize {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> usize {
        self
    }
}
impl SseDecode for InMemoryTodoRepository {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <RustOpaqueNom<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>,
        >>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
    }
}

impl SseDecode for chrono::DateTime<chrono::Utc> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i64>::sse_decode(deserializer);
        return chrono::DateTime::<chrono::Utc>::from_naive_utc_and_offset(
            chrono::DateTime::from_timestamp_micros(inner)
                .expect("invalid or out-of-range datetime")
                .naive_utc(),
            chrono::Utc,
        );
    }
}

impl SseDecode
    for RustOpaqueNom<
        flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return unsafe { decode_rust_opaque_nom(inner) };
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::domain::todo::todo_entity::Todo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::domain::todo::todo_entity::Todo>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Option<crate::domain::todo::todo_entity::Todo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::domain::todo::todo_entity::Todo>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::domain::todo::todo_entity::Todo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_createdAt = <chrono::DateTime<chrono::Utc>>::sse_decode(deserializer);
        let mut var_description = <String>::sse_decode(deserializer);
        let mut var_state = <crate::domain::todo::todo_state::TodoState>::sse_decode(deserializer);
        return crate::domain::todo::todo_entity::Todo {
            id: var_id,
            created_at: var_createdAt,
            description: var_description,
            state: var_state,
        };
    }
}

impl SseDecode for crate::domain::todo::todo_error::TodoError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::domain::todo::todo_error::TodoError::EmptyDescription,
            1 => crate::domain::todo::todo_error::TodoError::InvalidStateTransition,
            2 => crate::domain::todo::todo_error::TodoError::TodoNotFound,
            _ => unreachable!("Invalid variant for TodoError: {}", inner),
        };
    }
}

impl SseDecode for crate::domain::todo::todo_state::TodoState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::domain::todo::todo_state::TodoState::Todo,
            1 => crate::domain::todo::todo_state::TodoState::InProgress,
            2 => crate::domain::todo::todo_state::TodoState::Done,
            _ => unreachable!("Invalid variant for TodoState: {}", inner),
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<InMemoryTodoRepository> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, StdArc<_>>(self.0)
            .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<InMemoryTodoRepository>
{
}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<InMemoryTodoRepository>>
    for InMemoryTodoRepository
{
    fn into_into_dart(self) -> FrbWrapper<InMemoryTodoRepository> {
        self.into()
    }
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::domain::todo::todo_entity::Todo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.created_at.into_into_dart().into_dart(),
            self.description.into_into_dart().into_dart(),
            self.state.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::domain::todo::todo_entity::Todo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::domain::todo::todo_entity::Todo>
    for crate::domain::todo::todo_entity::Todo
{
    fn into_into_dart(self) -> crate::domain::todo::todo_entity::Todo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::domain::todo::todo_error::TodoError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::EmptyDescription => 0.into_dart(),
            Self::InvalidStateTransition => 1.into_dart(),
            Self::TodoNotFound => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::domain::todo::todo_error::TodoError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::domain::todo::todo_error::TodoError>
    for crate::domain::todo::todo_error::TodoError
{
    fn into_into_dart(self) -> crate::domain::todo::todo_error::TodoError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::domain::todo::todo_state::TodoState {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Todo => 0.into_dart(),
            Self::InProgress => 1.into_dart(),
            Self::Done => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::domain::todo::todo_state::TodoState
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::domain::todo::todo_state::TodoState>
    for crate::domain::todo::todo_state::TodoState
{
    fn into_into_dart(self) -> crate::domain::todo::todo_state::TodoState {
        self
    }
}

impl SseEncode for InMemoryTodoRepository {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <RustOpaqueNom<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>,
        >>::sse_encode(
            flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, StdArc<_>>(self),
            serializer,
        );
    }
}

impl SseEncode for chrono::DateTime<chrono::Utc> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.timestamp_micros(), serializer);
    }
}

impl SseEncode
    for RustOpaqueNom<
        flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::domain::todo::todo_entity::Todo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::domain::todo::todo_entity::Todo>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<crate::domain::todo::todo_entity::Todo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::domain::todo::todo_entity::Todo>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::domain::todo::todo_entity::Todo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <chrono::DateTime<chrono::Utc>>::sse_encode(self.created_at, serializer);
        <String>::sse_encode(self.description, serializer);
        <crate::domain::todo::todo_state::TodoState>::sse_encode(self.state, serializer);
    }
}

impl SseEncode for crate::domain::todo::todo_error::TodoError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::domain::todo::todo_error::TodoError::EmptyDescription => 0,
                crate::domain::todo::todo_error::TodoError::InvalidStateTransition => 1,
                crate::domain::todo::todo_error::TodoError::TodoNotFound => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::domain::todo::todo_state::TodoState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::domain::todo::todo_state::TodoState::Todo => 0,
                crate::domain::todo::todo_state::TodoState::InProgress => 1,
                crate::domain::todo::todo_state::TodoState::Done => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use crate::domain::todo::todo_repository::TodoRepository;
    use crate::infrastructure::repositories::todo::inmemory_todo_repository::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    // Section: dart2rust

    impl CstDecode<InMemoryTodoRepository> for usize {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> InMemoryTodoRepository {
            flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
                RustOpaqueNom<
                    flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>,
                >,
            >::cst_decode(
                self
            ))
        }
    }
    impl
        CstDecode<
            RustOpaqueNom<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>,
            >,
        > for usize
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(
            self,
        ) -> RustOpaqueNom<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>,
        > {
            unsafe { decode_rust_opaque_nom(self as _) }
        }
    }
    impl CstDecode<String> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            let vec: Vec<u8> = self.cst_decode();
            String::from_utf8(vec).unwrap()
        }
    }
    impl CstDecode<crate::domain::todo::todo_entity::Todo> for *mut wire_cst_todo {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::domain::todo::todo_entity::Todo {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::domain::todo::todo_entity::Todo>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl CstDecode<Vec<crate::domain::todo::todo_entity::Todo>> for *mut wire_cst_list_todo {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::domain::todo::todo_entity::Todo> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<crate::domain::todo::todo_entity::Todo> for wire_cst_todo {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::domain::todo::todo_entity::Todo {
            crate::domain::todo::todo_entity::Todo {
                id: self.id.cst_decode(),
                created_at: self.created_at.cst_decode(),
                description: self.description.cst_decode(),
                state: self.state.cst_decode(),
            }
        }
    }
    impl NewWithNullPtr for wire_cst_todo {
        fn new_with_null_ptr() -> Self {
            Self {
                id: core::ptr::null_mut(),
                created_at: Default::default(),
                description: core::ptr::null_mut(),
                state: Default::default(),
            }
        }
    }
    impl Default for wire_cst_todo {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_todo_dart_wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_delete(
        port_: i64,
        that: usize,
        id: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_delete_impl(port_, that, id)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_todo_dart_wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_find_all(
        port_: i64,
        that: usize,
    ) {
        wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_find_all_impl(port_, that)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_todo_dart_wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_find_by_id(
        port_: i64,
        that: usize,
        id: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_find_by_id_impl(port_, that, id)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_todo_dart_wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_save(
        port_: i64,
        that: usize,
        todo: *mut wire_cst_todo,
    ) {
        wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_save_impl(port_, that, todo)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_todo_dart_wire__crate__domain__todo__todo_state__todo_state_can_advance(
        port_: i64,
        that: i32,
    ) {
        wire__crate__domain__todo__todo_state__todo_state_can_advance_impl(port_, that)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_todo_dart_wire__crate__domain__todo__todo_state__todo_state_can_retreat(
        port_: i64,
        that: i32,
    ) {
        wire__crate__domain__todo__todo_state__todo_state_can_retreat_impl(port_, that)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_todo_dart_wire__crate__domain__todo__todo_state__todo_state_can_transition_to(
        port_: i64,
        that: i32,
        new_state: i32,
    ) {
        wire__crate__domain__todo__todo_state__todo_state_can_transition_to_impl(
            port_, that, new_state,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_todo_dart_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryTodoRepository(
        ptr: *const std::ffi::c_void,
    ) {
        unsafe {
            StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>>::increment_strong_count(ptr as _);
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_todo_dart_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryTodoRepository(
        ptr: *const std::ffi::c_void,
    ) {
        unsafe {
            StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>>::decrement_strong_count(ptr as _);
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_todo_dart_cst_new_box_autoadd_todo() -> *mut wire_cst_todo {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wire_cst_todo::new_with_null_ptr())
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_todo_dart_cst_new_list_prim_u_8_strict(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_8_strict {
        let ans = wire_cst_list_prim_u_8_strict {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_todo_dart_cst_new_list_todo(len: i32) -> *mut wire_cst_list_todo {
        let wrap = wire_cst_list_todo {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_todo>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_8_strict {
        ptr: *mut u8,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_todo {
        ptr: *mut wire_cst_todo,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_todo {
        id: *mut wire_cst_list_prim_u_8_strict,
        created_at: i64,
        description: *mut wire_cst_list_prim_u_8_strict,
        state: i32,
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use crate::domain::todo::todo_repository::TodoRepository;
    use crate::infrastructure::repositories::todo::inmemory_todo_repository::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    // Section: dart2rust

    impl CstDecode<String> for String {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            self
        }
    }
    impl CstDecode<Vec<u8>> for Box<[u8]> {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            self.into_vec()
        }
    }
    impl CstDecode<Vec<crate::domain::todo::todo_entity::Todo>>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::domain::todo::todo_entity::Todo> {
            self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap()
                .iter()
                .map(CstDecode::cst_decode)
                .collect()
        }
    }
    impl CstDecode<crate::domain::todo::todo_entity::Todo>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::domain::todo::todo_entity::Todo {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                4,
                "Expected 4 elements, got {}",
                self_.length()
            );
            crate::domain::todo::todo_entity::Todo {
                id: self_.get(0).cst_decode(),
                created_at: self_.get(1).cst_decode(),
                description: self_.get(2).cst_decode(),
                state: self_.get(3).cst_decode(),
            }
        }
    }
    impl CstDecode<InMemoryTodoRepository>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> InMemoryTodoRepository {
            flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
                RustOpaqueNom<
                    flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>,
                >,
            >::cst_decode(
                self
            ))
        }
    }
    impl CstDecode<chrono::DateTime<chrono::Utc>>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> chrono::DateTime<chrono::Utc> {
            CstDecode::<i64>::cst_decode(self).cst_decode()
        }
    }
    impl
        CstDecode<
            RustOpaqueNom<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>,
            >,
        > for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(
            self,
        ) -> RustOpaqueNom<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>,
        > {
            #[cfg(target_pointer_width = "64")]
            {
                compile_error!("64-bit pointers are not supported.");
            }
            unsafe { decode_rust_opaque_nom((self.as_f64().unwrap() as usize) as _) }
        }
    }
    impl CstDecode<String> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            self.as_string().expect("non-UTF-8 string, or not a string")
        }
    }
    impl CstDecode<bool> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> bool {
            self.is_truthy()
        }
    }
    impl CstDecode<i32> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> i32 {
            self.unchecked_into_f64() as _
        }
    }
    impl CstDecode<i64> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> i64 {
            ::std::convert::TryInto::<i64>::try_into(self).unwrap() as _
        }
    }
    impl CstDecode<Vec<u8>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            self.unchecked_into::<flutter_rust_bridge::for_generated::js_sys::Uint8Array>()
                .to_vec()
                .into()
        }
    }
    impl CstDecode<crate::domain::todo::todo_error::TodoError>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::domain::todo::todo_error::TodoError {
            (self.unchecked_into_f64() as i32).cst_decode()
        }
    }
    impl CstDecode<crate::domain::todo::todo_state::TodoState>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::domain::todo::todo_state::TodoState {
            (self.unchecked_into_f64() as i32).cst_decode()
        }
    }
    impl CstDecode<u8> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u8 {
            self.unchecked_into_f64() as _
        }
    }
    impl CstDecode<usize> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> usize {
            ::std::convert::TryInto::<u64>::try_into(self).unwrap() as _
        }
    }

    #[wasm_bindgen]
    pub fn wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_delete(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
        id: String,
    ) {
        wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_delete_impl(port_, that, id)
    }

    #[wasm_bindgen]
    pub fn wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_find_all(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    ) {
        wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_find_all_impl(port_, that)
    }

    #[wasm_bindgen]
    pub fn wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_find_by_id(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
        id: String,
    ) {
        wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_find_by_id_impl(port_, that, id)
    }

    #[wasm_bindgen]
    pub fn wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_save(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
        todo: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    ) {
        wire__crate__infrastructure__repositories__todo__inmemory_todo_repository__InMemoryTodoRepository_save_impl(port_, that, todo)
    }

    #[wasm_bindgen]
    pub fn wire__crate__domain__todo__todo_state__todo_state_can_advance(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        that: i32,
    ) {
        wire__crate__domain__todo__todo_state__todo_state_can_advance_impl(port_, that)
    }

    #[wasm_bindgen]
    pub fn wire__crate__domain__todo__todo_state__todo_state_can_retreat(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        that: i32,
    ) {
        wire__crate__domain__todo__todo_state__todo_state_can_retreat_impl(port_, that)
    }

    #[wasm_bindgen]
    pub fn wire__crate__domain__todo__todo_state__todo_state_can_transition_to(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        that: i32,
        new_state: i32,
    ) {
        wire__crate__domain__todo__todo_state__todo_state_can_transition_to_impl(
            port_, that, new_state,
        )
    }

    #[wasm_bindgen]
    pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryTodoRepository(
        ptr: *const std::ffi::c_void,
    ) {
        unsafe {
            StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>>::increment_strong_count(ptr as _);
        }
    }

    #[wasm_bindgen]
    pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryTodoRepository(
        ptr: *const std::ffi::c_void,
    ) {
        unsafe {
            StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryTodoRepository>>::decrement_strong_count(ptr as _);
        }
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
