// Dart-specific logo/header configuration
// This file contains custom logo or header information for Dart bindings

/// Custom logo/header for Dart-generated files
pub const DART_LOGO: &str = r#"
// ╔══════════════════════════════════════════════════════════════╗
// ║                    TODO DART BINDINGS                        ║
// ║         Generated by flutter_rust_bridge for Dart            ║
// ╚══════════════════════════════════════════════════════════════╝
"#;

